Context.create(name: 'phone', built_in: true)
Context.create(name: 'online', built_in: true)
Context.create(name: 'errands', built_in: true)
Context.create(name: 'offline', built_in: true)
Context.create(name: 'reading', built_in: true)
Context.create(name: 'in person', built_in: true)
Context.create(name: 'at home', built_in: true)
Context.create(name: 'at work', built_in: true)
Context.create(name: 'Launch Academy', built_in: true)

Task.create(body: 'call Mom', complete: true, context_id: 1)
Task.create(body: 'call Melly', complete: true, context_id: 1)
Task.create(body: 'call Merritt', complete: true, context_id: 1)
Task.create(body: 'order groceries', complete: true, context_id: 2)
Task.create(body: 'read POODR', complete: false, context_id: 5)
