Context.create(name: 'phone', built_in: true)
Context.create(name: 'online', built_in: true)
Context.create(name: 'errands', built_in: true)
Context.create(name: 'offline', built_in: true)
Context.create(name: 'reading', built_in: true)
Context.create(name: 'in person', built_in: true)
Context.create(name: 'at home', built_in: true)
Context.create(name: 'at work', built_in: true)
Context.create(name: 'Launch Academy', built_in: true)
